import { afterAll, beforeAll, expect, it } from "vitest";
import { eq } from "drizzle-orm";
import { addressHealthPolicies, cloudAccounts, cloudInstances, cloudInterfaces, cloudAddresses, managedAddressSlots, healthCheckConfigs, probeAgents } from "@masterdns/db";
import { fixture, testDatabase } from "./health-policy-test-utils.js";
import { HealthPoliciesService } from "./health-policies.service.js";
let connection: Awaited<ReturnType<typeof testDatabase>>;
let service: HealthPoliciesService;
beforeAll(async () => { connection = await testDatabase(); service = new HealthPoliciesService({ db: connection.db } as never); }, 30000);
afterAll(async () => { await connection?.dispose(); });
it("saves owner-scoped family policy with full-cohort defaults and idempotent revision", async () => {
 const f = await fixture(connection.db); const actor = f.actor as never;
 const input = { endpointId: f.endpoint.id, family: "4", configId: f.config.id, mode: "external", groupId: f.group.id };
 const first = await service.save(actor, input);
 expect(first).toMatchObject({ revision: 1, checkIntervalSeconds: 15, executionWindowSeconds: 10, resultExpirySeconds: 60, successThreshold: 3, consensus: { mode: "majority", minimumValid: 2 } });
 expect((await service.save(actor, input)).revision).toBe(1);
 const stranger = await fixture(connection.db);
 await expect(service.save(stranger.actor as never, input)).rejects.toMatchObject({ status: 404 });
 await expect(service.save(actor, { ...input, groupId: stranger.group.id })).rejects.toMatchObject({ status: 404 });
 await expect(service.save(actor, { ...input, networkPolicy: { allowedPrivateCIDRs: ["10.0.0.0/8"] } })).rejects.toMatchObject({ status: 403 });
 expect(await service.list(stranger.actor as never)).toHaveLength(0);
});
it("rejects unsupported-family assignment and incompatible external regex while preserving local JS", async () => {
 const f = await fixture(connection.db); const actor = f.actor as never;
 await connection.db.update(probeAgents).set({ capabilities: { ipv4: false, ipv6: true } }).where(eq(probeAgents.id, f.agents[0]!.id));
 const input = { endpointId: f.endpoint.id, family: "4", configId: f.config.id, mode: "external", groupId: f.group.id };
 await expect(service.save(actor, input)).rejects.toMatchObject({ status: 400 });
 await connection.db.update(probeAgents).set({ capabilities: { ipv4: true, ipv6: true } }).where(eq(probeAgents.id, f.agents[0]!.id));
 await connection.db.update(healthCheckConfigs).set({ checkerType: "http", config: { type: "http", bodyPattern: "a(?=b)" } }).where(eq(healthCheckConfigs.id, f.config.id));
 await expect(service.save(actor, input)).rejects.toThrow();
 expect(await service.save(actor, { ...input, mode: "local", groupId: undefined })).toMatchObject({ mode: "local" });
});
it("creates slot config without any linked endpoint and enforces family and ownership", async () => {
 const f = await fixture(connection.db); const actor = f.actor as never;
 const [account] = await connection.db.insert(cloudAccounts).values({ ownerUserId: f.actor.id, provider: "aws", name: "test", credentialCiphertext: "test", credentialIv: "test", credentialTag: "test" }).returning();
 const [instance] = await connection.db.insert(cloudInstances).values({ accountId: account!.id, service: "ec2", region: "test", externalId: "i-test", scanGeneration: 1 }).returning();
 const [nic] = await connection.db.insert(cloudInterfaces).values({ instanceId: instance!.id, externalId: "eni-test", scanGeneration: 1 }).returning();
 const [address] = await connection.db.insert(cloudAddresses).values({ interfaceId: nic!.id, kind: "host", family: "4", address: "192.0.2.20", origin: "user", scanGeneration: 1 }).returning();
 const [slot] = await connection.db.insert(managedAddressSlots).values({ interfaceId: nic!.id, family: "4", name: "primary", currentAddressId: address!.id }).returning();
 expect(await service.slotConfig(actor, slot!.id)).toBeNull();
 const config = await service.saveSlotConfig(actor, slot!.id, { config: { type: "tcp", port: 443 } });
 expect(config.slotId).toBe(slot!.id);
 expect((await service.slotConfig(actor, slot!.id))!.id).toBe(config.id);
 const stranger = await fixture(connection.db);
 await expect(service.slotConfig(stranger.actor as never, slot!.id)).rejects.toMatchObject({ status: 404 });
 const input = { slotId: slot!.id, family: "4", configId: config.id, mode: "external", groupId: f.group.id };
 expect(await service.save(actor, input)).toMatchObject({ slotId: slot!.id, endpointId: null });
 await expect(service.save(actor, { ...input, family: "6" })).rejects.toMatchObject({ status: 400 });
 expect(await connection.db.select().from(addressHealthPolicies).where(eq(addressHealthPolicies.slotId, slot!.id))).toHaveLength(1);
});
